[WIP] Attempt to run KitchenCI (docker) in TravisCI
StackStorm/chef-stackstorm pull request #22
Opened 2016-09-07 07:15 UTC by jvrplmlmn

Work in progress, don't mind me :)

2016-09-07 17:11 UTC, shortdudey123 commented
how about we not remove all the other testing :)

2016-09-18 19:30 UTC, jvrplmlmn commented
@shortdudey123 added back `rubocop`, `foodcritic` and `rspec`.

The Kitchen tests are failing for apparently unrelated issues.

2016-09-18 19:33 UTC, jvrplmlmn commented
https://stackstorm-community.slack.com/archives/community/p1474226956001831

2016-09-18 22:45 UTC, shortdudey123 commented on .travis.yml
> +  - /opt/chefdk/bin/cookstyle
Reason for switching? (besides copy and paste 😄)

2016-09-18 22:46 UTC, shortdudey123 commented on .travis.yml
> +     - chefdk
why do you need `chefdk`? looks like everything is already setup w/o it

2016-09-18 22:47 UTC, shortdudey123 commented on .travis.yml
> +  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/bin/kitchen verify ${INSTANCE}
Doesn't destroy at the end, not sure if that matters or not

2016-09-18 22:48 UTC, shortdudey123 commented on .travis.yml
> +  - /opt/chefdk/bin/foodcritic . --exclude spec
Why change the settings?

2016-09-19 22:58 UTC, shortdudey123 commented
Since `logrotate` is included in the base install of CentOS and Ubuntu but evidently not the docker images, you should be able to just add it to the `provision_command` section and call it good

2016-10-20 07:44 UTC, jvrplmlmn commented
Ran `kitchen` locally and the converge phase fails on the Ubuntu 14.04 box due to issues with the packagecloud repos:

```
(...)
Hit http://archive.ubuntu.com trusty/restricted amd64 Packages
Hit http://archive.ubuntu.com trusty/universe amd64 Packages
Get:2 https://packagecloud.io trusty/main Sources
Fetched 16.8 kB in 10s (1552 B/s)
W: Failed to fetch https://packagecloud.io/StackStorm/stable/ubuntu/dists/trusty/main/source/Sources  Hash Sum mismatch

W: Failed to fetch https://packagecloud.io/StackStorm/stable/ubuntu/dists/trusty/main/binary-amd64/Packages  Hash Sum mismatch

E: Some index files failed to download. They have been ignored, or old ones used instead.
(...)
```

@emedvedev ?

2016-10-20 18:34 UTC, shortdudey123 commented
@jvrplmlmn see http://blog.packagecloud.io/eng/2016/03/21/apt-hash-sum-mismatch/

2016-10-22 14:48 UTC, jvrplmlmn commented on .travis.yml
> +  - /opt/chefdk/bin/cookstyle
I'm used to `cookstyle`, which is based on `rubocop`. I think it has saner defaults.

2016-10-22 14:49 UTC, jvrplmlmn commented on .travis.yml
> +  - /opt/chefdk/bin/foodcritic . --exclude spec
Do you mean why we're excluding the `spec` directory?

2016-10-22 14:55 UTC, jvrplmlmn commented on .travis.yml
> +     - chefdk
We're installing the `chefdk` to have access to `cookstyle`, `foodcritic`, `rspec` and `kitchen` in the build.

Kitchen itself will install ChefDK in the Docker container where it runs the tests.

2016-10-22 14:56 UTC, jvrplmlmn commented on .travis.yml
> +  - KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/bin/kitchen verify ${INSTANCE}
This should be indeed `kitchen test` instead of `kitchen verify`. I'll push the change to see how it affects the build in TravisCI.

2016-10-23 08:52 UTC, jvrplmlmn commented
@shortdudey123 @sysbot @armab this is up for review. Let me know if you want me to squash the commits.

2016-10-23 13:31 UTC, armab commented
Thanks @jvrplmlmn for contributing and @shortdudey123 for reviewing!

Green build looks good enough to me :+1: but @shortdudey123 and @sysbot might have better idea about details.

2016-10-23 13:31 UTC, arm4b approved these changes

2016-10-23 18:19 UTC, shortdudey123 requested changes

2016-10-23 18:19 UTC, shortdudey123 commented on .travis.yml
> +  - /opt/chefdk/bin/cookstyle
we should stick with just one of them, not use both

2016-10-23 18:19 UTC, shortdudey123 commented on .travis.yml
> +  - /opt/chefdk/bin/foodcritic . --exclude spec
yes

2016-10-23 18:19 UTC, shortdudey123 commented on recipes/_packages.rb
> +package 'apt' do
needs spec test

2016-10-23 18:19 UTC, shortdudey123 commented on recipes/_packages.rb
> +execute 'Ubuntu Precise and Trusty: APT hash sum mismatch workaround' do
needs spec test

2016-10-23 18:19 UTC, shortdudey123 commented on .travis.yml
> +     - chefdk
We already installed everything needed except for kitchen

2016-10-23 18:59 UTC, shortdudey123 commented on recipes/_packages.rb
> +  only_if { %w(trusty precise).include? node['lsb']['codename'] }
combine the 2 `only_if`?

2016-11-14 18:24 UTC, armab commented
Since the build works in Travis, I think I'll go ahead and merge it.
We can change the small things afterwards.

2016-11-14 18:33 UTC, armab commented
Also, I'd change Docker images to those we already use for testing environment (shipped with `init` systems). See:
https://github.com/StackStorm/ansible-st2/blob/master/.kitchen.yml#L24-L39
https://hub.docker.com/r/stackstorm/packagingtest/tags/

@shortdudey123 Feel free to do after-merge changes as well.

2016-11-14 18:35 UTC, merged

2016-11-19 00:04 UTC, armab commented
Seeing now how helpful it is, would like to say big Thank You to @jvrplmlmn :tada: for implementation.