Multiplatform (Ubuntu 14.04 and Centos 7) ChefSpec testing
StackStorm/chef-stackstorm pull request #55
Opened 2016-12-08 22:06 UTC by jvrplmlmn

Solves https://github.com/StackStorm/chef-stackstorm/issues/54

It is my first time writing multi-platform ChefSpec, so probably there is room for improvement.

WDYT @armab @shortdudey123 ?

2016-12-08 22:20 UTC, armab commented
Thanks for trying it!

It looks pretty messed in Travis: ![](https://i.imgur.com/zAqaooZ.png)

Apart of that, is it possible just to loop through the platforms in spec where tests are 100% identical?
To avoid huge code duplication.
Otherwise, I'm not sure if this going to be helpful.

So expectation and reality differs here dramatically :smiley: Most probably we'll discourage writing tests with the way how it currently looks like.

Thoughts?

2016-12-08 22:41 UTC, jvrplmlmn commented
I have no idea why Travis shows that output...

When running `KITCHEN_LOCAL_YAML=.kitchen.docker.yml /opt/chefdk/bin/chef exec rake default` locally this is how the output is displayed:

![image](https://cloud.githubusercontent.com/assets/1429460/21030558/7b175c4e-bd9f-11e6-94b9-5ca1c3971a92.png)

2016-12-09 04:17 UTC, shortdudey123 approved these changes
I will look into the extra travis output again

2016-12-09 10:52 UTC, arm4b requested changes
As said, if we're going to just duplicate tests as it currently looks like, - I'm against this feature.

Think how it will look for 4 platforms.

Is it possible to loop through the platforms to avoid repeating same code again and again? Otherwise I'm +1 to keep things as it was before.

2016-12-09 13:09 UTC, jvrplmlmn commented
> Apart of that, is it possible just to loop through the platforms in spec where tests are 100% identical?
To avoid huge code duplication.
Otherwise, I'm not sure if this going to be helpful.

@armab take a look at 414275b, I managed to get it done for a single spec. I'll try to get the rest done later on.

2016-12-09 15:13 UTC, jvrplmlmn commented
I guess that there is some room for additional compactation in `spec/recipes/_packages_spec.rb`, but I think that the code its more readable as it is.

What about now @armab ?

2016-12-09 17:07 UTC, shortdudey123 commented
If you are looking to combine things, i would look at the `shared_examples ` rspec directive
http://modocache.io/shared-examples-in-rspec

2016-12-29 19:09 UTC, jvrplmlmn commented
@armab I've included the changes added on https://github.com/StackStorm/chef-stackstorm/pull/57, would you mind taking a look?

2016-12-31 13:15 UTC, arm4b approved these changes
I don't like duplicating `platforms` in every file and 2 levels of iterations,
but existing functionality is good enough and we can improve it later.

Additional thanks for rebasing and fixing new Rubocop issues, LGTM :+1:

2016-12-31 13:15 UTC, arm4b commented on spec/recipes/_services_spec.rb
> +  platforms = {
Looks better to me.

Do you think it's possible to include that in spec helper as single point of truth?

2016-12-31 13:15 UTC, arm4b commented on spec/recipes/_services_spec.rb
> +    versions.each do |version|
Also we'd need helper function to avoid 2 levels of iteration (platform + version) in `_spec` files and keep it clean.

2016-12-31 13:18 UTC, merged